package neo4j.cypher.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.cells.EditorCell;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.editor.runtime.selection.SelectionUtil;
import jetbrains.mps.openapi.editor.selection.SelectionManager;

public class DeleteConcreteSectionBracket {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.DELETE, new DeleteConcreteSectionBracket.DeleteConcreteSectionBracket_DELETE(node));
  }

  public static class DeleteConcreteSectionBracket_DELETE extends AbstractCellAction {
    /*package*/ SNode myNode;

    public DeleteConcreteSectionBracket_DELETE(SNode node) {
      this.myNode = node;
    }

    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }

    public void execute_internal(EditorContext editorContext, SNode node) {
      SPropertyOperations.set(node, "concrete", "" + (false));
      ListSequence.fromList(SLinkOperations.getTargets(node, "type", true)).clear();
      SPropertyOperations.set(node, "name", null);
      SPropertyOperations.set(node, "specifyHops", "" + (false));
      SPropertyOperations.set(node, "minHops", "" + (0));
      SPropertyOperations.set(node, "maxHops", "" + (0));
      ListSequence.fromList(SLinkOperations.getTargets(node, "property", true)).clear();
      SelectionUtil.selectCell(editorContext, node, SelectionManager.FIRST_EDITABLE_CELL);
    }
  }
}
