package neo4j.cypher.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.textGen.TextGenManager;

public class SkipStatement_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    if ((SLinkOperations.getTarget(node, "skipItems", true) != null)) {
      this.append("SKIP");
      TextGenManager.instance().appendNodeText(this.getContext(), this.getBuffer(), SLinkOperations.getTarget(node, "skipItems", true), this.getSNode());
      this.append(" ");
    }

    if ((SLinkOperations.getTarget(node, "limitItems", true) != null)) {
      this.append("LIMIT");
      TextGenManager.instance().appendNodeText(this.getContext(), this.getBuffer(), SLinkOperations.getTarget(node, "limitItems", true), this.getSNode());
    }

    if ((SLinkOperations.getTarget(node, "skipItems", true) != null) || (SLinkOperations.getTarget(node, "limitItems", true) != null)) {
      this.appendNewLine();
    }

  }
}
