package neo4j.cypher.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntention;
import jetbrains.mps.intentions.Intention;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class Asc2Desc_Intention extends BaseIntention implements Intention {
  public Asc2Desc_Intention() {
  }

  public String getConcept() {
    return "neo4j.cypher.structure.AscOrderBy";
  }

  public boolean isParameterized() {
    return false;
  }

  public boolean isErrorIntention() {
    return false;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public String getDescription(final SNode node, final EditorContext editorContext) {
    return "Converts ASC ordering into DESC";
  }

  public void execute(final SNode node, final EditorContext editorContext) {
    SNode descOrderBy = SConceptOperations.createNewNode("neo4j.cypher.structure.DescOrderBy", null);
    SLinkOperations.setTarget(descOrderBy, "expression", SNodeOperations.copyNode(SLinkOperations.getTarget(node, "expression", true)), true);
    SNodeOperations.replaceWithAnother(node, descOrderBy);
    editorContext.select(descOrderBy);
  }

  public String getLocationString() {
    return "neo4j.cypher.intentions";
  }
}
