package neo4j.cypher.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.intentions.IntentionExecutable;
import jetbrains.mps.intentions.IntentionType;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Collections;
import java.util.List;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.intentions.IntentionDescriptor;

public class ConvertNodeToNodeRef_Intention implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public ConvertNodeToNodeRef_Intention() {
  }

  public String getConcept() {
    return "neo4j.cypher.structure.Node";
  }

  public String getPresentation() {
    return "ConvertNodeToNodeRef";
  }

  public String getPersistentStateKey() {
    return "neo4j.cypher.intentions.ConvertNodeToNodeRef_Intention";
  }

  public String getLanguageFqName() {
    return "neo4j.cypher";
  }

  public IntentionType getType() {
    return IntentionType.NORMAL;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }

  public SNodeReference getIntentionNodeReference() {
    return new SNodePointer("r:4fb5ec9d-ba5b-4bca-9e48-d719ae880364(neo4j.cypher.intentions)", "6670155983237884464");
  }

  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new ConvertNodeToNodeRef_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }

  public class IntentionImplementation implements IntentionExecutable {
    public IntentionImplementation() {
    }

    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Converts node into node reference of the same name";
    }

    public void execute(final SNode node, final EditorContext editorContext) {
      List<SNode> nameNodes = SNodeOperations.getDescendants(SNodeOperations.getAncestor(node, "neo4j.cypher.structure.QueryExpression", false, false), "neo4j.cypher.structure.Node", false, new String[]{});

      for (SNode namedNode : nameNodes) {
        if (namedNode == node) {
          break;
        } else {
          if (SPropertyOperations.getString(namedNode, "name").equals(SPropertyOperations.getString(node, "name"))) {
            SNode newNodeRef = SConceptOperations.createNewNode("neo4j.cypher.structure.NamedNodeRef", null);
            SLinkOperations.setTarget(newNodeRef, "node1", namedNode, false);
            SNodeOperations.replaceWithAnother(node, newNodeRef);
            break;
          }
        }

      }
    }

    public IntentionDescriptor getDescriptor() {
      return ConvertNodeToNodeRef_Intention.this;
    }
  }
}
