package neo4j.cypher.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.intentions.IntentionExecutable;
import jetbrains.mps.intentions.IntentionType;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Collections;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;
import neo4j.cypher.behavior.Relationship_Behavior;
import jetbrains.mps.intentions.IntentionDescriptor;

public class ConvertToLRRelationship_Intention implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public ConvertToLRRelationship_Intention() {
  }

  public String getConcept() {
    return "neo4j.cypher.structure.Relationship";
  }

  public String getPresentation() {
    return "ConvertToLRRelationship";
  }

  public String getPersistentStateKey() {
    return "neo4j.cypher.intentions.ConvertToLRRelationship_Intention";
  }

  public String getLanguageFqName() {
    return "neo4j.cypher";
  }

  public IntentionType getType() {
    return IntentionType.NORMAL;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    if (!(isApplicableToNode(node, editorContext))) {
      return false;
    }
    return true;
  }

  private boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
    return !(SConceptOperations.isSubConceptOf(SNodeOperations.getConceptDeclaration(node), "neo4j.cypher.structure.LRRelationship"));
  }

  public SNodeReference getIntentionNodeReference() {
    return new SNodePointer("r:4fb5ec9d-ba5b-4bca-9e48-d719ae880364(neo4j.cypher.intentions)", "4409026550619394865");
  }

  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new ConvertToLRRelationship_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }

  public class IntentionImplementation implements IntentionExecutable {
    public IntentionImplementation() {
    }

    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Converts relationship to LR type";
    }

    public void execute(final SNode node, final EditorContext editorContext) {
      SNode newRelationship = SNodeFactoryOperations.replaceWithNewChild(node, "neo4j.cypher.structure.LRRelationship");
      Relationship_Behavior.call_copyConfigOf_4839691926370495851(newRelationship, node);
    }

    public IntentionDescriptor getDescriptor() {
      return ConvertToLRRelationship_Intention.this;
    }
  }
}
