package neo4j.cypher.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.intentions.IntentionExecutable;
import jetbrains.mps.intentions.IntentionType;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Collections;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.intentions.IntentionDescriptor;

public class ConvertWriteOnly2ReadWriteQuery_Intention implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public ConvertWriteOnly2ReadWriteQuery_Intention() {
  }

  public String getConcept() {
    return "neo4j.cypher.structure.WriteOnlyQueryExpression";
  }

  public String getPresentation() {
    return "ConvertWriteOnly2ReadWriteQuery";
  }

  public String getPersistentStateKey() {
    return "neo4j.cypher.intentions.ConvertWriteOnly2ReadWriteQuery_Intention";
  }

  public String getLanguageFqName() {
    return "neo4j.cypher";
  }

  public IntentionType getType() {
    return IntentionType.NORMAL;
  }

  public boolean isAvailableInChildNodes() {
    return true;
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }

  public SNodeReference getIntentionNodeReference() {
    return new SNodePointer("r:4fb5ec9d-ba5b-4bca-9e48-d719ae880364(neo4j.cypher.intentions)", "4768758963661559345");
  }

  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new ConvertWriteOnly2ReadWriteQuery_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }

  public class IntentionImplementation implements IntentionExecutable {
    public IntentionImplementation() {
    }

    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Converts write only query into read write query";
    }

    public void execute(final SNode node, final EditorContext editorContext) {
      SNode readWriteQueryExpression = SNodeFactoryOperations.replaceWithNewChild(node, "neo4j.cypher.structure.ReadWriteQueryExpression");

      ListSequence.fromList(SLinkOperations.getTargets(readWriteQueryExpression, "writeStatement", true)).clear();
      ListSequence.fromList(SLinkOperations.getTargets(readWriteQueryExpression, "writeStatement", true)).addElement(SLinkOperations.getTarget(node, "createStatement", true));
      ListSequence.fromList(SLinkOperations.getTargets(readWriteQueryExpression, "writeStatement", true)).addSequence(ListSequence.fromList(SLinkOperations.getTargets(node, "writeStatement", true)));
    }

    public IntentionDescriptor getDescriptor() {
      return ConvertWriteOnly2ReadWriteQuery_Intention.this;
    }
  }
}
