package neo4j.cypher.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.intentions.IntentionExecutable;
import jetbrains.mps.intentions.IntentionType;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Collections;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.intentions.IntentionDescriptor;

public class Desc2Asc_Intention implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public Desc2Asc_Intention() {
  }

  public String getConcept() {
    return "neo4j.cypher.structure.DescOrderBy";
  }

  public String getPresentation() {
    return "Desc2Asc";
  }

  public String getPersistentStateKey() {
    return "neo4j.cypher.intentions.Desc2Asc_Intention";
  }

  public String getLanguageFqName() {
    return "neo4j.cypher";
  }

  public IntentionType getType() {
    return IntentionType.NORMAL;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }

  public SNodeReference getIntentionNodeReference() {
    return new SNodePointer("r:4fb5ec9d-ba5b-4bca-9e48-d719ae880364(neo4j.cypher.intentions)", "7352030329465701064");
  }

  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new Desc2Asc_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }

  public class IntentionImplementation implements IntentionExecutable {
    public IntentionImplementation() {
    }

    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Converts DESC ordering into ASC";
    }

    public void execute(final SNode node, final EditorContext editorContext) {
      SNode ascOrderBy = SConceptOperations.createNewNode("neo4j.cypher.structure.AscOrderBy", null);
      SLinkOperations.setTarget(ascOrderBy, "expression", SNodeOperations.copyNode(SLinkOperations.getTarget(node, "expression", true)), true);
      SNodeOperations.replaceWithAnother(node, ascOrderBy);
      editorContext.select(ascOrderBy);
    }

    public IntentionDescriptor getDescriptor() {
      return Desc2Asc_Intention.this;
    }
  }
}
