package neo4j.cypher.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntention;
import jetbrains.mps.intentions.Intention;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class SwitchNodeInDefinitionMode_Intention extends BaseIntention implements Intention {
  public SwitchNodeInDefinitionMode_Intention() {
  }

  public String getConcept() {
    return "neo4j.cypher.structure.Node";
  }

  public boolean isParameterized() {
    return false;
  }

  public boolean isErrorIntention() {
    return false;
  }

  public boolean isAvailableInChildNodes() {
    return true;
  }

  public String getDescription(final SNode node, final EditorContext editorContext) {
    return "Switch on/off node definition mode to define node properties";
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    if (!(this.isApplicableToNode(node, editorContext))) {
      return false;
    }
    return true;
  }

  public boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
    return SNodeOperations.getAncestor(node, "neo4j.cypher.structure.CreateStatement", false, false) != null;
  }

  public void execute(final SNode node, final EditorContext editorContext) {
    SPropertyOperations.set(node, "inDefinitionMode", "" + (!(SPropertyOperations.getBoolean(node, "inDefinitionMode"))));
  }

  public String getLocationString() {
    return "neo4j.cypher.intentions";
  }
}
