package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AggregateFunction extends Function {
  public static final String concept = "neo4j.cypher.structure.AggregateFunction";
  public static final String EXPRESSION = "expression";

  public AggregateFunction(SNode node) {
    super(node);
  }

  public Expression getExpression() {
    return (Expression) this.getChild(Expression.class, AggregateFunction.EXPRESSION);
  }

  public void setExpression(Expression node) {
    super.setChild(AggregateFunction.EXPRESSION, node);
  }

  public static AggregateFunction newInstance(SModel sm, boolean init) {
    return (AggregateFunction) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.AggregateFunction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AggregateFunction newInstance(SModel sm) {
    return AggregateFunction.newInstance(sm, false);
  }
}
