package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AllExpression extends Expression implements ICypherExpression, IReturnExpression {
  public static final String concept = "neo4j.cypher.structure.AllExpression";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public AllExpression(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(AllExpression.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(AllExpression.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(AllExpression.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(AllExpression.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(AllExpression.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(AllExpression.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(AllExpression.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, AllExpression.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, AllExpression.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(AllExpression.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, AllExpression.SMODEL_ATTRIBUTE, node);
  }

  public static AllExpression newInstance(SModel sm, boolean init) {
    return (AllExpression) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.AllExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AllExpression newInstance(SModel sm) {
    return AllExpression.newInstance(sm, false);
  }
}
