package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AllIndex extends Index {
  public static final String concept = "neo4j.cypher.structure.AllIndex";

  public AllIndex(SNode node) {
    super(node);
  }

  public static AllIndex newInstance(SModel sm, boolean init) {
    return (AllIndex) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.AllIndex", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AllIndex newInstance(SModel sm) {
    return AllIndex.newInstance(sm, false);
  }
}
