package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AnyPredicateFunction extends PredicateFunction {
  public static final String concept = "neo4j.cypher.structure.AnyPredicateFunction";

  public AnyPredicateFunction(SNode node) {
    super(node);
  }

  public static AnyPredicateFunction newInstance(SModel sm, boolean init) {
    return (AnyPredicateFunction) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.AnyPredicateFunction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AnyPredicateFunction newInstance(SModel sm) {
    return AnyPredicateFunction.newInstance(sm, false);
  }
}
