package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ApStringLiteral extends Expression implements ICypherExpression {
  public static final String concept = "neo4j.cypher.structure.ApStringLiteral";
  public static final String VALUE = "value";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public ApStringLiteral(SNode node) {
    super(node);
  }

  public String getValue() {
    return this.getProperty(ApStringLiteral.VALUE);
  }

  public void setValue(String value) {
    this.setProperty(ApStringLiteral.VALUE, value);
  }

  public String getShortDescription() {
    return this.getProperty(ApStringLiteral.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(ApStringLiteral.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(ApStringLiteral.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(ApStringLiteral.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(ApStringLiteral.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(ApStringLiteral.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(ApStringLiteral.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, ApStringLiteral.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, ApStringLiteral.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(ApStringLiteral.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, ApStringLiteral.SMODEL_ATTRIBUTE, node);
  }

  public static ApStringLiteral newInstance(SModel sm, boolean init) {
    return (ApStringLiteral) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.ApStringLiteral", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ApStringLiteral newInstance(SModel sm) {
    return ApStringLiteral.newInstance(sm, false);
  }
}
