package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.lang.core.structure.Attribute;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Collection extends Expression implements IReturnExpression, ICollectionExpression {
  public static final String concept = "neo4j.cypher.structure.Collection";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String EXPRESSION = "expression";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Collection(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(Collection.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Collection.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Collection.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Collection.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Collection.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Collection.VIRTUAL_PACKAGE, value);
  }

  public int getExpressionsCount() {
    return this.getChildCount(Collection.EXPRESSION);
  }

  public Iterator<Expression> expressions() {
    return this.children(Expression.class, Collection.EXPRESSION);
  }

  public List<Expression> getExpressions() {
    return this.getChildren(Expression.class, Collection.EXPRESSION);
  }

  public void addExpression(Expression node) {
    this.addChild(Collection.EXPRESSION, node);
  }

  public void insertExpression(Expression prev, Expression node) {
    this.insertChild(prev, Collection.EXPRESSION, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Collection.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Collection.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Collection.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Collection.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Collection.SMODEL_ATTRIBUTE, node);
  }

  public static Collection newInstance(SModel sm, boolean init) {
    return (Collection) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.Collection", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Collection newInstance(SModel sm) {
    return Collection.newInstance(sm, false);
  }
}
