package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.MinusExpression;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CypherMinusExpression extends MinusExpression implements ICypherOperation {
  public static final String concept = "neo4j.cypher.structure.CypherMinusExpression";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public CypherMinusExpression(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(CypherMinusExpression.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(CypherMinusExpression.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(CypherMinusExpression.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(CypherMinusExpression.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(CypherMinusExpression.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(CypherMinusExpression.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(CypherMinusExpression.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, CypherMinusExpression.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, CypherMinusExpression.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(CypherMinusExpression.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, CypherMinusExpression.SMODEL_ATTRIBUTE, node);
  }

  public static CypherMinusExpression newInstance(SModel sm, boolean init) {
    return (CypherMinusExpression) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.CypherMinusExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CypherMinusExpression newInstance(SModel sm) {
    return CypherMinusExpression.newInstance(sm, false);
  }
}
