package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.NotEqualsExpression;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CypherNotEqualsExpression extends NotEqualsExpression implements ICypherOperation, IWhereExpression, IReturnExpression {
  public static final String concept = "neo4j.cypher.structure.CypherNotEqualsExpression";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public CypherNotEqualsExpression(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(CypherNotEqualsExpression.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(CypherNotEqualsExpression.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(CypherNotEqualsExpression.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(CypherNotEqualsExpression.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(CypherNotEqualsExpression.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(CypherNotEqualsExpression.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(CypherNotEqualsExpression.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, CypherNotEqualsExpression.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, CypherNotEqualsExpression.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(CypherNotEqualsExpression.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, CypherNotEqualsExpression.SMODEL_ATTRIBUTE, node);
  }

  public static CypherNotEqualsExpression newInstance(SModel sm, boolean init) {
    return (CypherNotEqualsExpression) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.CypherNotEqualsExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CypherNotEqualsExpression newInstance(SModel sm) {
    return CypherNotEqualsExpression.newInstance(sm, false);
  }
}
