package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CypherNodeType extends CypherPropertyContainerType {
  public static final String concept = "neo4j.cypher.structure.CypherNodeType";

  public CypherNodeType(SNode node) {
    super(node);
  }

  public static CypherNodeType newInstance(SModel sm, boolean init) {
    return (CypherNodeType) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.CypherNodeType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CypherNodeType newInstance(SModel sm) {
    return CypherNodeType.newInstance(sm, false);
  }
}
