package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class DescOrderBy extends OrderByExpression {
  public static final String concept = "neo4j.cypher.structure.DescOrderBy";

  public DescOrderBy(SNode node) {
    super(node);
  }

  public static DescOrderBy newInstance(SModel sm, boolean init) {
    return (DescOrderBy) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.DescOrderBy", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static DescOrderBy newInstance(SModel sm) {
    return DescOrderBy.newInstance(sm, false);
  }
}
