package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class EmbeddedConnection extends ConnectionStatement {
  public static final String concept = "neo4j.cypher.structure.EmbeddedConnection";

  public EmbeddedConnection(SNode node) {
    super(node);
  }

  public static EmbeddedConnection newInstance(SModel sm, boolean init) {
    return (EmbeddedConnection) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.EmbeddedConnection", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static EmbeddedConnection newInstance(SModel sm) {
    return EmbeddedConnection.newInstance(sm, false);
  }
}
