package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class EmptyConnectionStatement extends BaseConcept implements IConnectionStatement {
  public static final String concept = "neo4j.cypher.structure.EmptyConnectionStatement";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public EmptyConnectionStatement(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(EmptyConnectionStatement.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(EmptyConnectionStatement.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(EmptyConnectionStatement.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(EmptyConnectionStatement.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(EmptyConnectionStatement.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(EmptyConnectionStatement.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(EmptyConnectionStatement.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, EmptyConnectionStatement.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, EmptyConnectionStatement.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(EmptyConnectionStatement.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, EmptyConnectionStatement.SMODEL_ATTRIBUTE, node);
  }

  public static EmptyConnectionStatement newInstance(SModel sm, boolean init) {
    return (EmptyConnectionStatement) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.EmptyConnectionStatement", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static EmptyConnectionStatement newInstance(SModel sm) {
    return EmptyConnectionStatement.newInstance(sm, false);
  }
}
