package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class FilterCollFunction extends CollectionFunction {
  public static final String concept = "neo4j.cypher.structure.FilterCollFunction";

  public FilterCollFunction(SNode node) {
    super(node);
  }

  public static FilterCollFunction newInstance(SModel sm, boolean init) {
    return (FilterCollFunction) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.FilterCollFunction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static FilterCollFunction newInstance(SModel sm) {
    return FilterCollFunction.newInstance(sm, false);
  }
}
