package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.INamedConcept;

public interface INamedIdentifier extends INamedConcept {
  public static final String concept = "neo4j.cypher.structure.INamedIdentifier";
}
