package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface IWrite extends INodeAdapter {
  public static final String concept = "neo4j.cypher.structure.IWrite";
}
