package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.StringLiteral;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class KeyValueRelationshipIndex extends NamedIndex {
  public static final String concept = "neo4j.cypher.structure.KeyValueRelationshipIndex";
  public static final String KEY = "key";
  public static final String VALUE = "value";

  public KeyValueRelationshipIndex(SNode node) {
    super(node);
  }

  public String getKey() {
    return this.getProperty(KeyValueRelationshipIndex.KEY);
  }

  public void setKey(String value) {
    this.setProperty(KeyValueRelationshipIndex.KEY, value);
  }

  public StringLiteral getValue() {
    return (StringLiteral) this.getChild(StringLiteral.class, KeyValueRelationshipIndex.VALUE);
  }

  public void setValue(StringLiteral node) {
    super.setChild(KeyValueRelationshipIndex.VALUE, node);
  }

  public static KeyValueRelationshipIndex newInstance(SModel sm, boolean init) {
    return (KeyValueRelationshipIndex) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.KeyValueRelationshipIndex", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static KeyValueRelationshipIndex newInstance(SModel sm) {
    return KeyValueRelationshipIndex.newInstance(sm, false);
  }
}
