package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.StringLiteral;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class KeyValueNodeIndex extends NamedIndex {
  public static final String concept = "neo4j.cypher.structure.KeyValueNodeIndex";
  public static final String KEY = "key";
  public static final String VALUE = "value";

  public KeyValueNodeIndex(SNode node) {
    super(node);
  }

  public String getKey() {
    return this.getProperty(KeyValueNodeIndex.KEY);
  }

  public void setKey(String value) {
    this.setProperty(KeyValueNodeIndex.KEY, value);
  }

  public StringLiteral getValue() {
    return (StringLiteral) this.getChild(StringLiteral.class, KeyValueNodeIndex.VALUE);
  }

  public void setValue(StringLiteral node) {
    super.setChild(KeyValueNodeIndex.VALUE, node);
  }

  public static KeyValueNodeIndex newInstance(SModel sm, boolean init) {
    return (KeyValueNodeIndex) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.KeyValueNodeIndex", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static KeyValueNodeIndex newInstance(SModel sm) {
    return KeyValueNodeIndex.newInstance(sm, false);
  }
}
