package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class LowerMStringFunction extends ModifyStringFunction {
  public static final String concept = "neo4j.cypher.structure.LowerMStringFunction";

  public LowerMStringFunction(SNode node) {
    super(node);
  }

  public static LowerMStringFunction newInstance(SModel sm, boolean init) {
    return (LowerMStringFunction) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.LowerMStringFunction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static LowerMStringFunction newInstance(SModel sm) {
    return LowerMStringFunction.newInstance(sm, false);
  }
}
