package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class LRRelationship extends Relationship {
  public static final String concept = "neo4j.cypher.structure.LRRelationship";

  public LRRelationship(SNode node) {
    super(node);
  }

  public static LRRelationship newInstance(SModel sm, boolean init) {
    return (LRRelationship) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.LRRelationship", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static LRRelationship newInstance(SModel sm) {
    return LRRelationship.newInstance(sm, false);
  }
}
