package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MaxAggregate extends AggregateFunction {
  public static final String concept = "neo4j.cypher.structure.MaxAggregate";

  public MaxAggregate(SNode node) {
    super(node);
  }

  public static MaxAggregate newInstance(SModel sm, boolean init) {
    return (MaxAggregate) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.MaxAggregate", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static MaxAggregate newInstance(SModel sm) {
    return MaxAggregate.newInstance(sm, false);
  }
}
