package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NamedPathRef extends Expression implements ICypherExpression, IReturnExpression, IDeleteExpression {
  public static final String concept = "neo4j.cypher.structure.NamedPathRef";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String PATH_EXPRESSION = "pathExpression";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public NamedPathRef(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(NamedPathRef.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(NamedPathRef.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(NamedPathRef.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(NamedPathRef.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(NamedPathRef.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(NamedPathRef.VIRTUAL_PACKAGE, value);
  }

  public PathExpression getPathExpression() {
    return (PathExpression) this.getReferent(PathExpression.class, NamedPathRef.PATH_EXPRESSION);
  }

  public void setPathExpression(PathExpression node) {
    super.setReferent(NamedPathRef.PATH_EXPRESSION, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(NamedPathRef.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, NamedPathRef.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, NamedPathRef.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(NamedPathRef.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, NamedPathRef.SMODEL_ATTRIBUTE, node);
  }

  public static NamedPathRef newInstance(SModel sm, boolean init) {
    return (NamedPathRef) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.NamedPathRef", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NamedPathRef newInstance(SModel sm) {
    return NamedPathRef.newInstance(sm, false);
  }
}
