package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NamedPropertyContainerRef extends Expression implements ICypherExpression, IReturnExpression, IWhereExpression, IOrderByExpression, IDeleteExpression, ISetExpression {
  public static final String concept = "neo4j.cypher.structure.NamedPropertyContainerRef";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String PROPERTY_CONTAINER = "propertyContainer";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public NamedPropertyContainerRef(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(NamedPropertyContainerRef.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(NamedPropertyContainerRef.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(NamedPropertyContainerRef.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(NamedPropertyContainerRef.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(NamedPropertyContainerRef.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(NamedPropertyContainerRef.VIRTUAL_PACKAGE, value);
  }

  public IPropertyContainer getPropertyContainer() {
    return (IPropertyContainer) this.getReferent(IPropertyContainer.class, NamedPropertyContainerRef.PROPERTY_CONTAINER);
  }

  public void setPropertyContainer(IPropertyContainer node) {
    super.setReferent(NamedPropertyContainerRef.PROPERTY_CONTAINER, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(NamedPropertyContainerRef.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, NamedPropertyContainerRef.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, NamedPropertyContainerRef.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(NamedPropertyContainerRef.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, NamedPropertyContainerRef.SMODEL_ATTRIBUTE, node);
  }

  public static NamedPropertyContainerRef newInstance(SModel sm, boolean init) {
    return (NamedPropertyContainerRef) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.NamedPropertyContainerRef", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NamedPropertyContainerRef newInstance(SModel sm) {
    return NamedPropertyContainerRef.newInstance(sm, false);
  }
}
