package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NodesCollFunction extends CollectionFunction {
  public static final String concept = "neo4j.cypher.structure.NodesCollFunction";
  public static final String NAMED_RELATIONSHIP_REF = "namedRelationshipRef";

  public NodesCollFunction(SNode node) {
    super(node);
  }

  public NamedRelationshipRef getNamedRelationshipRef() {
    return (NamedRelationshipRef) this.getChild(NamedRelationshipRef.class, NodesCollFunction.NAMED_RELATIONSHIP_REF);
  }

  public void setNamedRelationshipRef(NamedRelationshipRef node) {
    super.setChild(NodesCollFunction.NAMED_RELATIONSHIP_REF, node);
  }

  public static NodesCollFunction newInstance(SModel sm, boolean init) {
    return (NodesCollFunction) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.NodesCollFunction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NodesCollFunction newInstance(SModel sm) {
    return NodesCollFunction.newInstance(sm, false);
  }
}
