package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class OrderByExpression extends Expression implements ICypherExpression, IOrderByExpression {
  public static final String concept = "neo4j.cypher.structure.OrderByExpression";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String EXPRESSION = "expression";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public OrderByExpression(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(OrderByExpression.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(OrderByExpression.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(OrderByExpression.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(OrderByExpression.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(OrderByExpression.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(OrderByExpression.VIRTUAL_PACKAGE, value);
  }

  public Expression getExpression() {
    return (Expression) this.getChild(Expression.class, OrderByExpression.EXPRESSION);
  }

  public void setExpression(Expression node) {
    super.setChild(OrderByExpression.EXPRESSION, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(OrderByExpression.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, OrderByExpression.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, OrderByExpression.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(OrderByExpression.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, OrderByExpression.SMODEL_ATTRIBUTE, node);
  }

  public static OrderByExpression newInstance(SModel sm, boolean init) {
    return (OrderByExpression) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.OrderByExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static OrderByExpression newInstance(SModel sm) {
    return OrderByExpression.newInstance(sm, false);
  }
}
