package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Parameter extends Expression implements ICypherExpression, INamedIdentifier, IReturnExpression, IOrderByExpression {
  public static final String concept = "neo4j.cypher.structure.Parameter";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String NAME = "name";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Parameter(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(Parameter.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Parameter.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Parameter.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Parameter.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Parameter.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Parameter.VIRTUAL_PACKAGE, value);
  }

  public String getName() {
    return this.getProperty(Parameter.NAME);
  }

  public void setName(String value) {
    this.setProperty(Parameter.NAME, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Parameter.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Parameter.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Parameter.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Parameter.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Parameter.SMODEL_ATTRIBUTE, node);
  }

  public static Parameter newInstance(SModel sm, boolean init) {
    return (Parameter) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.Parameter", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Parameter newInstance(SModel sm) {
    return Parameter.newInstance(sm, false);
  }
}
