package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.Expression;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PathFunction extends Function implements IMatchExpression {
  public static final String concept = "neo4j.cypher.structure.PathFunction";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String EXPRESSION = "expression";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public PathFunction(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(PathFunction.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(PathFunction.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(PathFunction.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(PathFunction.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(PathFunction.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(PathFunction.VIRTUAL_PACKAGE, value);
  }

  public Expression getExpression() {
    return (Expression) this.getChild(Expression.class, PathFunction.EXPRESSION);
  }

  public void setExpression(Expression node) {
    super.setChild(PathFunction.EXPRESSION, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(PathFunction.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, PathFunction.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, PathFunction.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(PathFunction.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, PathFunction.SMODEL_ATTRIBUTE, node);
  }

  public static PathFunction newInstance(SModel sm, boolean init) {
    return (PathFunction) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.PathFunction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PathFunction newInstance(SModel sm) {
    return PathFunction.newInstance(sm, false);
  }
}
