package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PercentileDiscAggregate extends AggregateFunction {
  public static final String concept = "neo4j.cypher.structure.PercentileDiscAggregate";

  public PercentileDiscAggregate(SNode node) {
    super(node);
  }

  public static PercentileDiscAggregate newInstance(SModel sm, boolean init) {
    return (PercentileDiscAggregate) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.PercentileDiscAggregate", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PercentileDiscAggregate newInstance(SModel sm) {
    return PercentileDiscAggregate.newInstance(sm, false);
  }
}
