package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PercentileContAggregate extends AggregateFunction {
  public static final String concept = "neo4j.cypher.structure.PercentileContAggregate";

  public PercentileContAggregate(SNode node) {
    super(node);
  }

  public static PercentileContAggregate newInstance(SModel sm, boolean init) {
    return (PercentileContAggregate) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.PercentileContAggregate", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PercentileContAggregate newInstance(SModel sm) {
    return PercentileContAggregate.newInstance(sm, false);
  }
}
