package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.baseLanguage.structure.IOperation;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PropertyOperation extends BaseConcept implements INamedNullableIdentifier, IOperation {
  public static final String concept = "neo4j.cypher.structure.PropertyOperation";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public PropertyOperation(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(PropertyOperation.NAME);
  }

  public void setName(String value) {
    this.setProperty(PropertyOperation.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(PropertyOperation.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(PropertyOperation.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(PropertyOperation.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(PropertyOperation.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(PropertyOperation.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(PropertyOperation.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(PropertyOperation.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, PropertyOperation.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, PropertyOperation.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(PropertyOperation.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, PropertyOperation.SMODEL_ATTRIBUTE, node);
  }

  public static PropertyOperation newInstance(SModel sm, boolean init) {
    return (PropertyOperation) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.PropertyOperation", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PropertyOperation newInstance(SModel sm) {
    return PropertyOperation.newInstance(sm, false);
  }
}
