package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class QueryExpression extends Expression {
  public static final String concept = "neo4j.cypher.structure.QueryExpression";

  public QueryExpression(SNode node) {
    super(node);
  }

  public static QueryExpression newInstance(SModel sm, boolean init) {
    return (QueryExpression) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.QueryExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static QueryExpression newInstance(SModel sm) {
    return QueryExpression.newInstance(sm, false);
  }
}
