package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class RangeCollFunction extends CollectionFunction {
  public static final String concept = "neo4j.cypher.structure.RangeCollFunction";
  public static final String START = "start";
  public static final String END = "end";
  public static final String STEP = "step";

  public RangeCollFunction(SNode node) {
    super(node);
  }

  public Expression getStart() {
    return (Expression) this.getChild(Expression.class, RangeCollFunction.START);
  }

  public void setStart(Expression node) {
    super.setChild(RangeCollFunction.START, node);
  }

  public Expression getEnd() {
    return (Expression) this.getChild(Expression.class, RangeCollFunction.END);
  }

  public void setEnd(Expression node) {
    super.setChild(RangeCollFunction.END, node);
  }

  public Expression getStep() {
    return (Expression) this.getChild(Expression.class, RangeCollFunction.STEP);
  }

  public void setStep(Expression node) {
    super.setChild(RangeCollFunction.STEP, node);
  }

  public static RangeCollFunction newInstance(SModel sm, boolean init) {
    return (RangeCollFunction) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.RangeCollFunction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static RangeCollFunction newInstance(SModel sm) {
    return RangeCollFunction.newInstance(sm, false);
  }
}
