package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class RLRelationship extends Relationship {
  public static final String concept = "neo4j.cypher.structure.RLRelationship";

  public RLRelationship(SNode node) {
    super(node);
  }

  public static RLRelationship newInstance(SModel sm, boolean init) {
    return (RLRelationship) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.RLRelationship", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static RLRelationship newInstance(SModel sm) {
    return RLRelationship.newInstance(sm, false);
  }
}
