package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class RoundMathFunction extends MathFunction {
  public static final String concept = "neo4j.cypher.structure.RoundMathFunction";

  public RoundMathFunction(SNode node) {
    super(node);
  }

  public static RoundMathFunction newInstance(SModel sm, boolean init) {
    return (RoundMathFunction) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.RoundMathFunction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static RoundMathFunction newInstance(SModel sm) {
    return RoundMathFunction.newInstance(sm, false);
  }
}
