package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ScalarFunction extends Function {
  public static final String concept = "neo4j.cypher.structure.ScalarFunction";

  public ScalarFunction(SNode node) {
    super(node);
  }

  public static ScalarFunction newInstance(SModel sm, boolean init) {
    return (ScalarFunction) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.ScalarFunction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ScalarFunction newInstance(SModel sm) {
    return ScalarFunction.newInstance(sm, false);
  }
}
