package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ShortestPathFunction extends PathFunction {
  public static final String concept = "neo4j.cypher.structure.ShortestPathFunction";

  public ShortestPathFunction(SNode node) {
    super(node);
  }

  public static ShortestPathFunction newInstance(SModel sm, boolean init) {
    return (ShortestPathFunction) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.ShortestPathFunction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ShortestPathFunction newInstance(SModel sm) {
    return ShortestPathFunction.newInstance(sm, false);
  }
}
