package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SqrtMathFunction extends MathFunction {
  public static final String concept = "neo4j.cypher.structure.SqrtMathFunction";

  public SqrtMathFunction(SNode node) {
    super(node);
  }

  public static SqrtMathFunction newInstance(SModel sm, boolean init) {
    return (SqrtMathFunction) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.SqrtMathFunction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SqrtMathFunction newInstance(SModel sm) {
    return SqrtMathFunction.newInstance(sm, false);
  }
}
