package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class StartAssignmentStatement extends BaseConcept {
  public static final String concept = "neo4j.cypher.structure.StartAssignmentStatement";
  public static final String NODE1 = "node1";
  public static final String INDEX = "index";

  public StartAssignmentStatement(SNode node) {
    super(node);
  }

  public Node getNode1() {
    return (Node) this.getChild(Node.class, StartAssignmentStatement.NODE1);
  }

  public void setNode1(Node node) {
    super.setChild(StartAssignmentStatement.NODE1, node);
  }

  public Index getIndex() {
    return (Index) this.getChild(Index.class, StartAssignmentStatement.INDEX);
  }

  public void setIndex(Index node) {
    super.setChild(StartAssignmentStatement.INDEX, node);
  }

  public static StartAssignmentStatement newInstance(SModel sm, boolean init) {
    return (StartAssignmentStatement) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.StartAssignmentStatement", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static StartAssignmentStatement newInstance(SModel sm) {
    return StartAssignmentStatement.newInstance(sm, false);
  }
}
