package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class StrStringFunction extends StringFunction {
  public static final String concept = "neo4j.cypher.structure.StrStringFunction";
  public static final String EXPRESSION = "expression";

  public StrStringFunction(SNode node) {
    super(node);
  }

  public Expression getExpression() {
    return (Expression) this.getChild(Expression.class, StrStringFunction.EXPRESSION);
  }

  public void setExpression(Expression node) {
    super.setChild(StrStringFunction.EXPRESSION, node);
  }

  public static StrStringFunction newInstance(SModel sm, boolean init) {
    return (StrStringFunction) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.StrStringFunction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static StrStringFunction newInstance(SModel sm) {
    return StrStringFunction.newInstance(sm, false);
  }
}
