package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TimestampScalarFunction extends ScalarFunction {
  public static final String concept = "neo4j.cypher.structure.TimestampScalarFunction";

  public TimestampScalarFunction(SNode node) {
    super(node);
  }

  public static TimestampScalarFunction newInstance(SModel sm, boolean init) {
    return (TimestampScalarFunction) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.TimestampScalarFunction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TimestampScalarFunction newInstance(SModel sm) {
    return TimestampScalarFunction.newInstance(sm, false);
  }
}
