package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TypeScalarFunction extends ScalarFunction {
  public static final String concept = "neo4j.cypher.structure.TypeScalarFunction";
  public static final String NAMED_RELATIONSHIP_REF = "namedRelationshipRef";

  public TypeScalarFunction(SNode node) {
    super(node);
  }

  public NamedRelationshipRef getNamedRelationshipRef() {
    return (NamedRelationshipRef) this.getChild(NamedRelationshipRef.class, TypeScalarFunction.NAMED_RELATIONSHIP_REF);
  }

  public void setNamedRelationshipRef(NamedRelationshipRef node) {
    super.setChild(TypeScalarFunction.NAMED_RELATIONSHIP_REF, node);
  }

  public static TypeScalarFunction newInstance(SModel sm, boolean init) {
    return (TypeScalarFunction) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.TypeScalarFunction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TypeScalarFunction newInstance(SModel sm) {
    return TypeScalarFunction.newInstance(sm, false);
  }
}
