package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class UndirectedRelationship extends Relationship {
  public static final String concept = "neo4j.cypher.structure.UndirectedRelationship";

  public UndirectedRelationship(SNode node) {
    super(node);
  }

  public static UndirectedRelationship newInstance(SModel sm, boolean init) {
    return (UndirectedRelationship) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.UndirectedRelationship", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static UndirectedRelationship newInstance(SModel sm) {
    return UndirectedRelationship.newInstance(sm, false);
  }
}
