package neo4j.cypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class WhereStatement extends CypherStatement {
  public static final String concept = "neo4j.cypher.structure.WhereStatement";
  public static final String EXPRESSION = "expression";

  public WhereStatement(SNode node) {
    super(node);
  }

  public Expression getExpression() {
    return (Expression) this.getChild(Expression.class, WhereStatement.EXPRESSION);
  }

  public void setExpression(Expression node) {
    super.setChild(WhereStatement.EXPRESSION, node);
  }

  public static WhereStatement newInstance(SModel sm, boolean init) {
    return (WhereStatement) SModelUtil_new.instantiateConceptDeclaration("neo4j.cypher.structure.WhereStatement", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static WhereStatement newInstance(SModel sm) {
    return WhereStatement.newInstance(sm, false);
  }
}
