package neo4j.cypher.sandbox.sandbox;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.tuples.runtime.Tuples;
import jetbrains.mps.baseLanguage.tuples.runtime.MultiTuple;
import java.util.List;

public class ExampleJavaIntegrationWithTuples {


  public static void main(String[] args) {
    Tuples._2<Integer, String> tplexample = MultiTuple.<Integer,String>from(5435, "dfsd");

    ExampleNamedTuple exampleNamedTuple = new ExampleNamedTuple("John", 45, 443);

    List<String> list;

    System.out.println("example" + tplexample);
    System.out.println("example tuple call:" + getExampleNamedTuple());

    String readOnlyQuery = "START tuplenode = node(*), tuplenode2 = node(*) RETURN tuplenode,tuplenode2,\"str1\",\"str2\" ";

    System.out.println("typed:" + readOnlyQuery);
  }



  public static ExampleNamedTuple getExampleNamedTuple() {
    System.out.println("example named tuple");

    return new ExampleNamedTuple("Bill", 64, 453);
  }




}
