package neo4j.cypher.actions;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.action.NodeSetupContext;

public class QueriesGenerated {
  public static void nodeFactory_NodeSetup_AssignmentStatement_5206628397327285756(final IOperationContext operationContext, final NodeSetupContext _context) {
    // <node> 
  }
}
