package neo4j.cypher.behavior;

/*Generated by MPS */


public class AllIndex_BehaviorDescriptor extends Index_BehaviorDescriptor {
  public AllIndex_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.AllIndex";
  }
}
