package neo4j.cypher.behavior;

/*Generated by MPS */


public class AnyPredicateFunction_BehaviorDescriptor extends PredicateFunction_BehaviorDescriptor {
  public AnyPredicateFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.AnyPredicateFunction";
  }
}
