package neo4j.cypher.behavior;

/*Generated by MPS */


public class AvgAggregate_BehaviorDescriptor extends AggregateFunction_BehaviorDescriptor {
  public AvgAggregate_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.AvgAggregate";
  }
}
