package neo4j.cypher.behavior;

/*Generated by MPS */


public class CoalesceScalarFunction_BehaviorDescriptor extends ScalarFunction_BehaviorDescriptor {
  public CoalesceScalarFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.CoalesceScalarFunction";
  }
}
