package neo4j.cypher.behavior;

/*Generated by MPS */


public abstract class CollectionFunction_BehaviorDescriptor extends Function_BehaviorDescriptor {
  public CollectionFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.CollectionFunction";
  }
}
