package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Type_BehaviorDescriptor;

public class CypherCollectionType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public CypherCollectionType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.CypherCollectionType";
  }
}
