package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.DotExpression_BehaviorDescriptor;

public class CypherDotExpression_BehaviorDescriptor extends DotExpression_BehaviorDescriptor implements IReturnExpression_BehaviorDescriptor {
  public CypherDotExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.CypherDotExpression";
  }
}
