package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.AndExpression_BehaviorDescriptor;

public class CypherAndExpression_BehaviorDescriptor extends AndExpression_BehaviorDescriptor implements ICypherOperation_BehaviorDescriptor, IWhereExpression_BehaviorDescriptor, IReturnExpression_BehaviorDescriptor {
  public CypherAndExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.CypherAndExpression";
  }
}
