package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Type_BehaviorDescriptor;

public class CypherPropertyContainerType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public CypherPropertyContainerType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.CypherPropertyContainerType";
  }
}
