package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.MinusExpression_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.project.IModule;

public class CypherMinusExpression_BehaviorDescriptor extends MinusExpression_BehaviorDescriptor implements ICypherOperation_BehaviorDescriptor {
  public CypherMinusExpression_BehaviorDescriptor() {
  }

  public Object virtual_eval_1213877519769(SNode thisNode, IModule module) {
    return CypherMinusExpression_Behavior.virtual_eval_1213877519769(thisNode, module);
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.CypherMinusExpression";
  }
}
