package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.IntegerLiteral_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.module.SModule;

public class CypherIntegerConstant_BehaviorDescriptor extends IntegerLiteral_BehaviorDescriptor implements ICypherExpression_BehaviorDescriptor, IDontSubstituteByDefault_BehaviorDescriptor {
  public CypherIntegerConstant_BehaviorDescriptor() {
  }

  public boolean virtual_constant_1262430001741498050(SConcept thisConcept) {
    return CypherIntegerConstant_Behavior.virtual_constant_1262430001741498050(thisConcept);
  }

  public Object virtual_eval_1213877519769(SNode thisNode, SModule module) {
    return CypherIntegerConstant_Behavior.virtual_eval_1213877519769(thisNode, module);
  }

  public Object virtual_getCompileTimeConstantValue_1238860310638(SNode thisNode, SModule module) {
    return CypherIntegerConstant_Behavior.virtual_getCompileTimeConstantValue_1238860310638(thisNode, module);
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.CypherIntegerConstant";
  }
}
