package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.NotEqualsExpression_BehaviorDescriptor;

public class CypherNotEqualsExpression_BehaviorDescriptor extends NotEqualsExpression_BehaviorDescriptor implements ICypherOperation_BehaviorDescriptor, IWhereExpression_BehaviorDescriptor, IReturnExpression_BehaviorDescriptor {
  public CypherNotEqualsExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.CypherNotEqualsExpression";
  }
}
