package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.MulExpression_BehaviorDescriptor;

public class CypherMulExpression_BehaviorDescriptor extends MulExpression_BehaviorDescriptor implements ICypherOperation_BehaviorDescriptor {
  public CypherMulExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.CypherMulExpression";
  }
}
