package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Type_BehaviorDescriptor;

public class CypherResultIteratorTupleType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public CypherResultIteratorTupleType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.CypherResultIteratorTupleType";
  }
}
