package neo4j.cypher.behavior;

/*Generated by MPS */


public class DescOrderBy_BehaviorDescriptor extends OrderByExpression_BehaviorDescriptor {
  public DescOrderBy_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.DescOrderBy";
  }
}
