package neo4j.cypher.behavior;

/*Generated by MPS */


public class DistinctReturnExpression_BehaviorDescriptor extends ReturnExpression_BehaviorDescriptor {
  public DistinctReturnExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.DistinctReturnExpression";
  }
}
