package neo4j.cypher.behavior;

/*Generated by MPS */


public class EmptyNode_BehaviorDescriptor extends Node_BehaviorDescriptor {
  public EmptyNode_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.EmptyNode";
  }
}
