package neo4j.cypher.behavior;

/*Generated by MPS */


public class ExtractCollFunction_BehaviorDescriptor extends CollectionFunction_BehaviorDescriptor {
  public ExtractCollFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.ExtractCollFunction";
  }
}
