package neo4j.cypher.behavior;

/*Generated by MPS */


public class FilterCollFunction_BehaviorDescriptor extends CollectionFunction_BehaviorDescriptor {
  public FilterCollFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.FilterCollFunction";
  }
}
