package neo4j.cypher.behavior;

/*Generated by MPS */


public class HeadCollFunction_BehaviorDescriptor extends CollectionFunction_BehaviorDescriptor {
  public HeadCollFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.HeadCollFunction";
  }
}
