package neo4j.cypher.behavior;

/*Generated by MPS */


public class IdIndex_BehaviorDescriptor extends Index_BehaviorDescriptor {
  public IdIndex_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.IdIndex";
  }
}
