package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public interface INamedIdentifier_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor {
}
