package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class INamedIdentifier_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean isCorrectIdentifierName_5206628397327427489(String name) {
    if (name == null) {
      return true;
    }

    // backtited value 
    if (name.length() >= 2 && name.charAt(0) == '`' && name.charAt(name.length() - 1) == '`') {
      // check inner pairing of backtites 
      String inner = name.substring(1, name.length() - 1).replace("``", "");
      if (inner.contains("`")) {
        return false;
      }

      return true;
    }

    // no backtited value - only alphanumeric chars, first char must be alpha 
    if (name.length() > 0) {
      if (!(name.matches("[a-zA-Z$[_]][a-zA-Z0-9$[_]]*"))) {
        return false;
      }
    }

    return true;
  }
}
