package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class IPropertyContainer_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean call_isNamedContainer_1951399816900233224(SNode thisNode) {
    return isNotEmpty_22lelj_a0a0b(SPropertyOperations.getString(thisNode, "name"));
  }

  public static boolean isNotEmpty_22lelj_a0a0b(String str) {
    return str != null && str.length() > 0;
  }
}
