package neo4j.cypher.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public interface IWriteStatement_BehaviorDescriptor {
  public void virtual_joinWithTheSameNodeType_8020740480872452998(SNode thisNode, SNode iWriteStatement);
}
