package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import jetbrains.mps.smodel.language.ConceptRegistry;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class IWriteStatement_Behavior {
  private static Class[] PARAMETERS_8020740480872452998 = {SNode.class, SNode.class};

  public static void init(SNode thisNode) {
  }

  public static void call_joinWithTheSameNodeType_8020740480872452998(SNode thisNode, SNode iWriteStatement) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getBehaviorDescriptorForInstanceNode(thisNode);
    descriptor.invoke(Object.class, SNodeOperations.cast(thisNode, "neo4j.cypher.structure.IWriteStatement"), "virtual_joinWithTheSameNodeType_8020740480872452998", PARAMETERS_8020740480872452998, new Object[]{iWriteStatement});
  }

  public static void callSuper_joinWithTheSameNodeType_8020740480872452998(SNode thisNode, String callerConceptFqName, SNode iWriteStatement) {
    BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "neo4j.cypher.structure.IWriteStatement"), callerConceptFqName, "virtual_joinWithTheSameNodeType_8020740480872452998", PARAMETERS_8020740480872452998, new Object[]{iWriteStatement});
  }
}
