package neo4j.cypher.behavior;

/*Generated by MPS */


public class LastScalarFunction_BehaviorDescriptor extends ScalarFunction_BehaviorDescriptor {
  public LastScalarFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.LastScalarFunction";
  }
}
