package neo4j.cypher.behavior;

/*Generated by MPS */


public class LeftMStringFunction_BehaviorDescriptor extends ModifyStringFunction_BehaviorDescriptor {
  public LeftMStringFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.LeftMStringFunction";
  }
}
