package neo4j.cypher.behavior;

/*Generated by MPS */


public class LuceneIndex_BehaviorDescriptor extends NamedIndex_BehaviorDescriptor {
  public LuceneIndex_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.LuceneIndex";
  }
}
