package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class MatchStatement_BehaviorDescriptor extends CypherStatement_BehaviorDescriptor {
  public MatchStatement_BehaviorDescriptor() {
  }

  public int virtual_getOrder_6384283002380928985(SNode thisNode) {
    return MatchStatement_Behavior.virtual_getOrder_6384283002380928985(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.MatchStatement";
  }
}
