package neo4j.cypher.behavior;

/*Generated by MPS */


public abstract class MatchStatement_BehaviorDescriptor extends CypherStatement_BehaviorDescriptor {
  public MatchStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.MatchStatement";
  }
}
