package neo4j.cypher.behavior;

/*Generated by MPS */


public class MinAggregate_BehaviorDescriptor extends AggregateFunction_BehaviorDescriptor {
  public MinAggregate_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.MinAggregate";
  }
}
