package neo4j.cypher.behavior;

/*Generated by MPS */


public class ModifyStringFunction_BehaviorDescriptor extends StringFunction_BehaviorDescriptor {
  public ModifyStringFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.ModifyStringFunction";
  }
}
