package neo4j.cypher.behavior;

/*Generated by MPS */


public class NamedNodeReference_BehaviorDescriptor extends ReturnExpression_BehaviorDescriptor {
  public NamedNodeReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.NamedNodeReference";
  }
}
