package neo4j.cypher.behavior;

/*Generated by MPS */


public class NamedUntypedRLRelationship_BehaviorDescriptor extends Relationship_BehaviorDescriptor {
  public NamedUntypedRLRelationship_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.NamedUntypedRLRelationship";
  }
}
