package neo4j.cypher.behavior;

/*Generated by MPS */


public class NamedTypedRelationship_BehaviorDescriptor extends Relationship_BehaviorDescriptor {
  public NamedTypedRelationship_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.NamedTypedRelationship";
  }
}
