package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class NamedRelationshipRef_BehaviorDescriptor extends Expression_BehaviorDescriptor implements IReturnExpression_BehaviorDescriptor, IOrderByExpression_BehaviorDescriptor {
  public NamedRelationshipRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.NamedRelationshipRef";
  }
}
