package neo4j.cypher.behavior;

/*Generated by MPS */


public class NamedNode_BehaviorDescriptor extends Node_BehaviorDescriptor implements INamedPropertyContainer_BehaviorDescriptor {
  public NamedNode_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.NamedNode";
  }
}
