package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class NamedNodeRef_BehaviorDescriptor extends Expression_BehaviorDescriptor implements ICypherExpression_BehaviorDescriptor, IMatchExpression_BehaviorDescriptor, ICreateExpression_BehaviorDescriptor {
  public NamedNodeRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.NamedNodeRef";
  }
}
