package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class NamedUntypedRelationship_BehaviorDescriptor extends Relationship_BehaviorDescriptor implements INamedPropertyContainer_BehaviorDescriptor {
  public NamedUntypedRelationship_BehaviorDescriptor() {
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.NamedUntypedRelationship";
  }
}
