package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class Neo4jExec_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public Neo4jExec_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.Neo4jExec";
  }
}
