package neo4j.cypher.behavior;

/*Generated by MPS */


public abstract class Node_BehaviorDescriptor extends PropertyContainer_BehaviorDescriptor {
  public Node_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.Node";
  }
}
