package neo4j.cypher.behavior;

/*Generated by MPS */


public class NodesCollFunction_BehaviorDescriptor extends CollectionFunction_BehaviorDescriptor {
  public NodesCollFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.NodesCollFunction";
  }
}
