package neo4j.cypher.behavior;

/*Generated by MPS */


public class NonePredicateFunction_BehaviorDescriptor extends PredicateFunction_BehaviorDescriptor {
  public NonePredicateFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.NonePredicateFunction";
  }
}
