package neo4j.cypher.behavior;

/*Generated by MPS */


public class OrderByStatement_BehaviorDescriptor extends CypherStatement_BehaviorDescriptor {
  public OrderByStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.OrderByStatement";
  }
}
