package neo4j.cypher.behavior;

/*Generated by MPS */


public abstract class OrderByExpression_BehaviorDescriptor extends CypherExpression_BehaviorDescriptor {
  public OrderByExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.OrderByExpression";
  }
}
