package neo4j.cypher.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class Parameter_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean call_isCorrectParameterName_5206628397327481277(SAbstractConcept thisConcept, String name) {
    if (name == null) {
      return true;
    }

    if (name.matches("[a-zA-Z][a-zA-Z0-9]*")) {
      return true;
    }
    if (name.matches("[0-9]*")) {
      return true;
    }

    return false;
  }
}
