package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class PredicateExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor implements IReturnExpression_BehaviorDescriptor {
  public PredicateExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.PredicateExpression";
  }
}
