package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class PropertyContainer_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public PropertyContainer_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.PropertyContainer";
  }
}
