package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public abstract class QueryExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public QueryExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.QueryExpression";
  }
}
