package neo4j.cypher.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class ReadWriteQueryTupleExpression_BehaviorDescriptor extends ReadWriteQueryExpression_BehaviorDescriptor implements QueryTupleExpression_BehaviorDescriptor {
  public ReadWriteQueryTupleExpression_BehaviorDescriptor() {
  }

  public SNode virtual_getReturnStatement_5915353355198811340(SNode thisNode) {
    return ReadWriteQueryTupleExpression_Behavior.virtual_getReturnStatement_5915353355198811340(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.ReadWriteQueryTupleExpression";
  }
}
