package neo4j.cypher.behavior;

/*Generated by MPS */


public class ReduceCollFunction_BehaviorDescriptor extends CollectionFunction_BehaviorDescriptor {
  public ReduceCollFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.ReduceCollFunction";
  }
}
