package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class Relationship_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean call_isRealAnonymous_4409026550619645624(SNode thisNode) {
    return isEmpty_ck02f0_a0a0a1(SPropertyOperations.getString(thisNode, "name")) && ListSequence.fromList(SLinkOperations.getTargets(thisNode, "type", true)).isEmpty();
  }

  public static boolean call_isNamed_4409026550619536514(SNode thisNode) {
    return isNotEmpty_ck02f0_a0a0c(SPropertyOperations.getString(thisNode, "name"));
  }

  public static boolean call_isTyped_4409026550619536574(SNode thisNode) {
    return ListSequence.fromList(SLinkOperations.getTargets(thisNode, "type", true)).isNotEmpty();
  }

  public static boolean isEmpty_ck02f0_a0a0a1(String str) {
    return str == null || str.length() == 0;
  }

  public static boolean isNotEmpty_ck02f0_a0a0c(String str) {
    return str != null && str.length() > 0;
  }
}
