package neo4j.cypher.behavior;

/*Generated by MPS */


public class RelsPathFunction_BehaviorDescriptor extends PathFunction_BehaviorDescriptor {
  public RelsPathFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.RelsPathFunction";
  }
}
