package neo4j.cypher.behavior;

/*Generated by MPS */


public class ReplaceMStringFunction_BehaviorDescriptor extends ModifyStringFunction_BehaviorDescriptor {
  public ReplaceMStringFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.ReplaceMStringFunction";
  }
}
