package neo4j.cypher.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class ReturnStatementBlock_BehaviorDescriptor extends CypherStatement_BehaviorDescriptor {
  public ReturnStatementBlock_BehaviorDescriptor() {
  }

  public int virtual_getOrder_6384283002380928985(SNode thisNode) {
    return ReturnStatementBlock_Behavior.virtual_getOrder_6384283002380928985(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.ReturnStatementBlock";
  }
}
