package neo4j.cypher.behavior;

/*Generated by MPS */


public class RoundMathFunction_BehaviorDescriptor extends MathFunction_BehaviorDescriptor {
  public RoundMathFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.RoundMathFunction";
  }
}
