package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class SetStatement_BehaviorDescriptor extends CypherStatement_BehaviorDescriptor implements IWriteStatement_BehaviorDescriptor {
  public SetStatement_BehaviorDescriptor() {
  }

  public int virtual_getOrder_6384283002380928985(SNode thisNode) {
    return SetStatement_Behavior.virtual_getOrder_6384283002380928985(thisNode);
  }

  public void virtual_joinWithTheSameNodeType_8020740480872452998(SNode thisNode, SNode otherIWriteStatement) {
    SetStatement_Behavior.virtual_joinWithTheSameNodeType_8020740480872452998(thisNode, otherIWriteStatement);
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.SetStatement";
  }
}
