package neo4j.cypher.behavior;

/*Generated by MPS */


public class ShortestPathFunction_BehaviorDescriptor extends PathFunction_BehaviorDescriptor {
  public ShortestPathFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.ShortestPathFunction";
  }
}
