package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.behavior.Expression_Behavior;

public class SubstringMStringFunction_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean call_isNegativeInteger_1325020284374205965(SNode thisNode, SNode expression) {
    // <node> 
    try {
      Object eval = Expression_Behavior.call_eval_1213877519769(expression, null);
      if (eval instanceof Integer) {
        return as_x5ltvq_a0a0a1a1a1(eval, Integer.class) < 0;
      }

    } catch (UnsupportedOperationException exception) {
    }

    return false;
  }

  private static <T> T as_x5ltvq_a0a0a1a1a1(Object o, Class<T> type) {
    return (type.isInstance(o) ?
      (T) o :
      null
    );
  }
}
