package neo4j.cypher.behavior;

/*Generated by MPS */


public class SumAggregate_BehaviorDescriptor extends AggregateFunction_BehaviorDescriptor {
  public SumAggregate_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.SumAggregate";
  }
}
