package neo4j.cypher.behavior;

/*Generated by MPS */


public class TrimMStringFunction_BehaviorDescriptor extends ModifyStringFunction_BehaviorDescriptor {
  public TrimMStringFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.TrimMStringFunction";
  }
}
