package neo4j.cypher.behavior;

/*Generated by MPS */


public class TypeScalarFunction_BehaviorDescriptor extends ScalarFunction_BehaviorDescriptor {
  public TypeScalarFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.TypeScalarFunction";
  }
}
