package neo4j.cypher.behavior;

/*Generated by MPS */


public class UndirectedRelationship_BehaviorDescriptor extends Relationship_BehaviorDescriptor {
  public UndirectedRelationship_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.UndirectedRelationship";
  }
}
