package neo4j.cypher.behavior;

/*Generated by MPS */


public class UnnamedUntypedRLRelationship_BehaviorDescriptor extends Relationship_BehaviorDescriptor {
  public UnnamedUntypedRLRelationship_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.UnnamedUntypedRLRelationship";
  }
}
