package neo4j.cypher.behavior;

/*Generated by MPS */


public class UnnamedTypedRLRelationship_BehaviorDescriptor extends Relationship_BehaviorDescriptor {
  public UnnamedTypedRLRelationship_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.UnnamedTypedRLRelationship";
  }
}
