package neo4j.cypher.behavior;

/*Generated by MPS */


public class UnnamedTypedLRRelationship_BehaviorDescriptor extends Relationship_BehaviorDescriptor {
  public UnnamedTypedLRRelationship_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.UnnamedTypedLRRelationship";
  }
}
