package neo4j.cypher.behavior;

/*Generated by MPS */


public class UnnamedNode_BehaviorDescriptor extends Node_BehaviorDescriptor {
  public UnnamedNode_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.UnnamedNode";
  }
}
