package neo4j.cypher.behavior;

/*Generated by MPS */


public class UnnamedUntypedRelationship_BehaviorDescriptor extends Relationship_BehaviorDescriptor {
  public UnnamedUntypedRelationship_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.UnnamedUntypedRelationship";
  }
}
