package neo4j.cypher.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public class UnnamedTypedRelationship_BehaviorDescriptor extends Relationship_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public UnnamedTypedRelationship_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.UnnamedTypedRelationship";
  }
}
