package neo4j.cypher.behavior;

/*Generated by MPS */


public class UpperMStringFunction_BehaviorDescriptor extends ModifyStringFunction_BehaviorDescriptor {
  public UpperMStringFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.UpperMStringFunction";
  }
}
