package neo4j.cypher.behavior;

/*Generated by MPS */


public abstract class WhereExpression_BehaviorDescriptor extends CypherExpression_BehaviorDescriptor {
  public WhereExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.WhereExpression";
  }
}
