package neo4j.cypher.behavior;

/*Generated by MPS */


public class WriteOnlyQueryStringExpression_BehaviorDescriptor extends WriteOnlyQueryExpression_BehaviorDescriptor implements QueryStringExpression_BehaviorDescriptor {
  public WriteOnlyQueryStringExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.WriteOnlyQueryStringExpression";
  }
}
