package neo4j.cypher.behavior;

/*Generated by MPS */


public class WriteOnlyQueryExpression_BehaviorDescriptor extends QueryExpression_BehaviorDescriptor {
  public WriteOnlyQueryExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "neo4j.cypher.structure.WriteOnlyQueryExpression";
  }
}
